name: flutter_application_todo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  equatable: ^2.0.5
  http: ^1.2.2
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  flutter_datetime_picker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
